language: ruby

rvm:
  - 3.1.0 # Upgrade Ruby to 3.1.0

services:
  - docker

before_install:
  # Install dpl for deployment with compatible Ruby version
  - rvm use 3.1.0 --fuzzy do ruby -S gem install dpl -v 2.0.5.1

  # DockerHub login check with exit condition
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin || exit 1
  - docker info # Check Docker login status
script:
  # Build Docker images for each project
  # - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  # - docker build -t udagram-frontend ./udagram-frontend
  # - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  # Tag Docker images for DockerHub
  # - docker tag udagram-api-feed $DOCKER_USERNAME/udagram-api-feed:v1
  - docker tag udagram-api-user $DOCKER_USERNAME/udagram-api-user:v1
  # - docker tag udagram-frontend $DOCKER_USERNAME/udagram-frontend:v1
  # - docker tag udagram-reverseproxy $DOCKER_USERNAME/udagram-reverseproxy:v1
  - docker images
deploy:
  provider: script
  script:
    echo "Pushing udagram-api-user..."
    docker push $DOCKER_USERNAME/udagram-api-user:v1
    # echo "Pushing udagram-api-feed..."
    # docker push $DOCKER_USERNAME/udagram-api-feed:v1
    # echo "Pushing udagram-frontend..."
    # docker push $DOCKER_USERNAME/udagram-frontend:v1
    # echo "Pushing udagram-reverseproxy..."
    # docker push $DOCKER_USERNAME/udagram-reverseproxy:v1
  on:
    branch: main
