language: minimal

services:
  - docker

before_install:
  # Install compatible excon version for Ruby 2.4.5
  - gem install excon -v 0.109.0
  # Install dpl for deployment
  - rvm use $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl -v 2.0.5.1
  # DockerHub login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  # Build Docker images for each project
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  # Tag Docker images for DockerHub
  - docker tag udagram-api-feed $DOCKER_USERNAME/udagram-api-feed:v1
  - docker tag udagram-api-user $DOCKER_USERNAME/udagram-api-user:v1
  - docker tag udagram-frontend $DOCKER_USERNAME/udagram-frontend:v1
  - docker tag udagram-reverseproxy $DOCKER_USERNAME/udagram-reverseproxy:v1

deploy:
  provider: script
  script:
    # Push Docker images to DockerHub
    - docker push $DOCKER_USERNAME/udagram-api-feed:v1
    - docker push $DOCKER_USERNAME/udagram-api-user:v1
    - docker push $DOCKER_USERNAME/udagram-frontend:v1
    - docker push $DOCKER_USERNAME/udagram-reverseproxy:v1
  on:
    branch: main
