language: minimal

services:
  - docker

before_install:
  # DockerHub login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  # Build images for each project
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  # Tag images for DockerHub
  - docker tag udagram-api-feed $DOCKER_USERNAME/udagram-api-feed:v1
  - docker tag udagram-api-user $DOCKER_USERNAME/udagram-api-user:v1
  - docker tag udagram-frontend $DOCKER_USERNAME/udagram-frontend:v1
  - docker tag udagram-reverseproxy $DOCKER_USERNAME/udagram-reverseproxy:v1

deploy:
  provider: script
  script:
    # Push images to DockerHub
    - docker push $DOCKER_USERNAME/udagram-api-feed:v1
    - docker push $DOCKER_USERNAME/udagram-api-user:v1
    - docker push $DOCKER_USERNAME/udagram-frontend:v1
    - docker push $DOCKER_USERNAME/udagram-reverseproxy:v1
  on:
    branch: main
