language: ruby

rvm:
  - 3.1.0 # Upgrade Ruby to 3.1.0

services:
  - docker

before_install:
  # Install dpl for deployment with compatible Ruby version
  - rvm use 3.1.0 --fuzzy do ruby -S gem install dpl -v 2.0.5.1

  # DockerHub login check with exit condition
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin || exit 1
script:
  # Build Docker images for each project
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  # Tag Docker images for DockerHub
  - docker tag udagram-reverseproxy $DOCKER_USERNAME/udagram-reverseproxy:v1
  - docker images
deploy:
  provider: script
  script: |
    echo "Pushing udagram-reverseproxy..."
    docker push $DOCKER_USERNAME/udagram-reverseproxy:v1
  on:
    branch: main
