apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-service
  labels:
    service: reverseproxy
spec:
  selector:
    service: reverseproxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
